name: check-mkdocs
on: [pull_request]

jobs:
  build:
    name: "Checking docs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout main"
        uses: actions/checkout@v1
      - name: "Building docs"
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
